---
- name: install and configure wordpress
  hosts: wp-servers
  become: yes
  vars:
    db_name: "wordpress"
    db_username: "wordpress"
  tasks:
    - name: install packages 
      block:
        - name: incloud os-specific vars for Debian family 
          include_vars: "{{ ansible_os_family }}.yaml" 
        - name: install apache2 
          package: 
            name: {{ packages.apache}}
            state: latest 
            update_cache: yes
          notify: restart apache2
        - name: install mysql
          package: 
            name: {{ packages.mysql }}
            state: latest 
            update_cache: yes
          notify: restart mysql
        - name: install prerequisties required packages
          package:
            name: {{ packages.prerequisties }}
            state: present
            update_cache: yes
      tags:
        - download-packages 

    - name: configure db 
      block:
        - name: delete anonymous user on mysql
          mysql_user:
            name: ''
            host: localhost
            state: absent
            login_unix_socket: /run/mysqld/mysqld.sock
        - name: secure mysql root user
          mysql_user:
            name: root
            host: "{{ item }}"
            login_user: root
            login_password: ""
            login_unix_socket: /run/mysqld/mysqld.sock
          with_items:
            - localhost
        - name: create wp database
          mysql_db:
            name: "{{ db_name }}"
            state: present
            login_user: root
            login_password: ""
        - name: generate a password for wp user
          command: openssl rand -hex 7
          register: db_password
        - name: create mysql for database wp
          mysql_user:
            name: "{{ db_username }}"
            password: "{{ db_password.stdout }}"
            host: localhost
            login_user: root
            login_password: ""
            priv: "{{ db_name }}.*:ALL"
            login_unix_socket: /run/mysqld/mysqld.sock
        - name: present password
          debug:
            msg: "The password of wordpress database is: {{ db_password.stdout }}"
      tags:
        - create-WPDB
    - name: install wp 
      block:
        - name: download wp
          unarchive:
            src: https://wordpress.org/latest.tar.gz
            dest: /var/www
            remote_src: yes
      rescue:
        - name: download unzip 
          package: 
            name:
              - unzip 
            state: latest 
            update_cache: yes 
        - name: download wp
          unarchive:
            src: https://wordpress.org/latest.tar.zip
            dest: /var/www
            remote_src: yes
      tags:
        - download
    - name: configure wp 
      block:
        - name: update default apache website configure
          lineinfile:
            path: /etc/apache2/sites-available/000-default.conf
            regexp: '^(\s*)DocumentRoot \/var\/www\/html'
            line: '\1DocumentRoot /var/www/wordpress'
            backrefs: yes
          notify: restart apache2
        - name: create wp-config file
          ansible.builtin.copy:
            src: /var/www/wordpress/wp-config-sample.php
            dest: /var/www/wordpress/wp-config.php
            owner: www-data
            group: www-data
            mode: '0644'
            remote_src: yes
        - name: modify wp-config
          lineinfile:
            path: /var/www/wordpress/wp-config.php
            regexp: "{{ item.find }}"
            line: "{{ item.replace }}"
          with_items:
            - { "find": "define\\(.'DB_NAME',.+\\);", "replace": "define( 'DB_NAME', '{{ db_name }}' );" }
            - { "find": "define\\(.'DB_USER',.+\\);", "replace": "define( 'DB_USER', '{{ db_username }}' );" }
            - { "find": "define\\(.'DB_PASSWORD',.+\\);", "replace": "define( 'DB_PASSWORD', '{{ db_password.stdout }}' );" }

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
        enabled: yes 
    - name: restart mysql 
      service:
        name: mysql.service
        state: restarted
        enabled: yes 
